version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing app
      - TAG_IMAGE=$(git tag --sort=-creatordate | head -n 1)
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $TAG_IMAGE
# Include only the files required for your application to run.
artifacts:
  files:
    - src/server.js
    - package.json
    - node_modules/**/*
