apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web-app
spec:
  containers:
  - name: alpine
    image: alpine
    command:
    - /bin/sh -c
    tty: true
  - name: node-12
    image: node-12
    command:
    - /bin/sh -c
    tty: true
  - name: k8s-kubectl
    image: jshimko/kube-tools-aws
    command:
    - /bin/sh -c
    tty: true
