apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web-app
spec:
  containers:
  - name: alpine
    image: alpine
    command:
    - cat
    tty: true
    env:
    - name: CONTAINER_ENV_VAR
      value: busybox
